version: '3.8'

services:
  genaigithub:
    image: pr-reviewer-api
    volumes:
      - ${PGSSLROOTCERT}:/etc/postgres/certs/ca-certificate.crt
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGSSLROOTCERT: /etc/postgres/certs/ca-certificate.crt
      PGSSLMODE: verify-full
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "8000:8000"
