LANGUAGE_MAPPING = {
    "cpp": "cpp",
    "go": "go",
    "java": "java",
    "kt": "kotlin",
    "js": "js",
    "ts": "ts",
    "php": "php",
    "proto": "proto",
    "py": "python",
    "rst": "rst",
    "rb": "ruby",
    "rs": "rust",
    "scala": "scala",
    "swift": "swift",
    "md": "markdown",
    "tex": "latex",
    "html": "html",
    "sol": "sol",
    "cs": "csharp",
    "cbl": "cobol",
    "c": "c",
    "lua": "lua",
    "pl": "perl",
    "hs": "haskell",
    "ex": "elixir",
    "ps1": "powershell",
}
